# Generated by Django 6.0.2 on 2026-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="my_number",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
