# Generated by Django 6.0.2 on 2026-02-16 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="製造番号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "稼働中"),
                            ("MAINTENANCE", "整備中"),
                            ("DECOMMISSIONED", "除籍"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "assigned_unit",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="配備部隊"
                    ),
                ),
                (
                    "deployment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="配備日"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                (
                    "flight_hours",
                    models.FloatField(default=0.0, verbose_name="飛行時間"),
                ),
                (
                    "engine_type",
                    models.CharField(max_length=100, verbose_name="エンジン型式"),
                ),
            ],
            options={
                "verbose_name": "航空機",
                "verbose_name_plural": "航空機",
            },
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Firearm",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                ("caliber", models.CharField(max_length=20, verbose_name="口径")),
                (
                    "rounds_fired",
                    models.IntegerField(default=0, verbose_name="総発射弾数"),
                ),
            ],
            options={
                "verbose_name": "火器",
                "verbose_name_plural": "火器",
            },
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                (
                    "mileage",
                    models.FloatField(default=0.0, verbose_name="走行距離(km)"),
                ),
                (
                    "armor_type",
                    models.CharField(max_length=100, verbose_name="装甲タイプ"),
                ),
            ],
            options={
                "verbose_name": "車両",
                "verbose_name_plural": "車両",
            },
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                ("displacement", models.FloatField(verbose_name="排水量(トン)")),
                ("max_speed", models.FloatField(verbose_name="最大速力(ノット)")),
            ],
            options={
                "verbose_name": "艦艇",
                "verbose_name_plural": "艦艇",
            },
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="DeploymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_unit",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="旧部隊"
                    ),
                ),
                ("new_unit", models.CharField(max_length=100, verbose_name="新部隊")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="異動日"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="異動理由")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="logistics.equipment",
                        verbose_name="装備品",
                    ),
                ),
            ],
        ),
    ]
