# Generated by Django 6.0.2 on 2026-02-16 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Maintenance"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("acquisition_date", models.DateField()),
                (
                    "required_clearance",
                    models.CharField(
                        choices=[
                            ("CONFIDENTIAL", "Confidential"),
                            ("SECRET", "Secret"),
                            ("TOP_SECRET", "Top Secret"),
                        ],
                        default="CONFIDENTIAL",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                ("flight_hours", models.IntegerField(default=0)),
                ("max_altitude", models.IntegerField(help_text="In feet")),
            ],
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Firearm",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                ("caliber", models.CharField(max_length=20)),
                ("rate_of_fire", models.IntegerField(help_text="Rounds per minute")),
            ],
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                ("mileage", models.IntegerField(default=0)),
                ("transmission_type", models.CharField(max_length=20)),
            ],
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="logistics.equipment",
                    ),
                ),
                ("displacement", models.IntegerField(help_text="In tons")),
                ("max_speed", models.IntegerField(help_text="In knots")),
            ],
            bases=("logistics.equipment",),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_location", models.CharField(max_length=100)),
                (
                    "commanding_officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commanded_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="logistics.unit",
            ),
        ),
    ]
