# Generated by Django 6.0.2 on 2026-02-16 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymenthistory",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="異動日"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="deployment_date",
            field=models.DateField(default=datetime.date.today, verbose_name="配備日"),
        ),
    ]
