# Generated by Django 6.0.2 on 2026-02-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("logistics", "0002_alter_deploymenthistory_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.clearancelevel",
                verbose_name="機密区分",
            ),
        ),
    ]
