# Generated by Django 6.0.2 on 2026-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "duration_frames",
                    models.PositiveIntegerField(help_text="Duration in frames (30fps)"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("MXF", "MXF"), ("MP4", "MP4"), ("MOV", "QuickTime")],
                        default="MXF",
                        max_length=10,
                    ),
                ),
                (
                    "som",
                    models.CharField(
                        default="00:00:00:00",
                        help_text="Start of Message Timecode (HH:MM:SS:FF)",
                        max_length=11,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
