# Generated by Django 6.0.2 on 2026-02-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("CIV", "Civil"),
                            ("CRM", "Criminal"),
                            ("FAM", "Family"),
                            ("ADM", "Administrative"),
                        ],
                        max_length=3,
                    ),
                ),
                ("filing_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("CLO", "Closed"),
                            ("APP", "Appeal"),
                            ("HLD", "On Hold"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to the physical file", max_length=500
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("doc_type", models.CharField(max_length=50)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearings",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("PLA", "Plaintiff"),
                            ("DEF", "Defendant"),
                            ("LAW", "Lawyer"),
                            ("JUD", "Judge"),
                            ("WIT", "Witness"),
                        ],
                        max_length=3,
                    ),
                ),
                ("contact_info", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="cases.case",
                    ),
                ),
            ],
        ),
    ]
