# Generated by Django 6.0.2 on 2026-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("case_type", models.CharField(max_length=3)),
                ("last_serial", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("year", "case_type")},
            },
        ),
    ]
