# Generated by Django 6.0.2 on 2026-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casesequence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
