apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  # WARNING: DO NOT USE THESE VALUES IN PRODUCTION.
  # This file is a template. Replace with secure, randomly generated secrets.
  # Use base64 encoded values.

  # cookie: secret-cookie
  rabbitmq-erlang-cookie: c2VjcmV0LWNvb2tpZQ==
  # user: admin
  rabbitmq-default-user: YWRtaW4=
  # pass: password
  rabbitmq-default-pass: cGFzc3dvcmQ=
  # url: amqp://admin:password@rabbitmq:5672/
  # Ensure the credentials in the URL match the user/pass above.
  rabbitmq-endpoint-url: YW1xcDovL2FkbWluOnBhc3N3b3JkQHJhYmJpdG1xOjU2NzIv
