apiVersion: v1
kind: Secret
metadata:
  name: banking-core-secret
type: Opaque
data:
  # Base64 encoded placeholders
  DB_USER: "YWRtaW4=" # admin
  DB_PASSWORD: "cGFzc3dvcmQ=" # password
  JWT_SECRET: "c2VjcmV0" # secret
