# Generated by Django 6.0.2 on 2026-02-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelfareRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateField(auto_now_add=True)),
                ("ended_at", models.DateField(blank=True, null=True)),
                (
                    "resident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welfare_recipient",
                        to="residents.resident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistance_type",
                    models.CharField(
                        choices=[
                            ("LIVELIHOOD_PROTECTION", "Livelihood Protection"),
                            ("DISABILITY_SUPPORT", "Disability Support"),
                            ("CHILD_ALLOWANCE", "Child Allowance"),
                            ("ELDERLY_CARE", "Elderly Care"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_provided", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistance_records",
                        to="welfare.welfarerecipient",
                    ),
                ),
            ],
        ),
    ]
